interview/urls.py
from django.urls import path

from interview import views

app_name = "interview"
urlpatterns = [
    path("<uuid:uuid>/", view=views.details, name="details"),
    path("create/<int:job_pk>/", view=views.create, name="create"),
    path(
        "<uuid:chat_uuid>/create-message/",
        view=views.create_message,
        name="create_message",
    ),
]

job/urls.py
from django.urls import path

from job import views

app_name = "job"
urlpatterns = [
    path("", views.list, name="list"),
    path("<int:pk>/", views.details, name="details"),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("job/", include("job.urls")),
    path("interview/", include("interview.urls")),
]

core/models.py
from django.db import models

# Create your models here.

interview/models.py
import uuid
from enum import Enum
from functools import reduce

from django.conf import settings
from django.db import models
from django.urls import reverse


class MessageRole(Enum):
    SYSTEM = "system"
    ASSISTANT = "assistant"
    USER = "user"

    @classmethod
    def choices(cls):
        return [(key.value, key.value) for key in cls]


class Message(models.Model):
    chat = models.ForeignKey(
        "interview.Chat", on_delete=models.CASCADE, related_name="messages"
    )
    role = models.CharField(max_length=10, choices=MessageRole.choices())
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.role} - {self.chat.title}"


class Chat(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False)
    title = models.CharField(max_length=100, editable=False)
    job = models.ForeignKey("job.Job", on_delete=models.CASCADE, related_name="chats")
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.uuid:
            self.uuid = uuid.uuid4()
            self.title = f"Chat {self.job.title} - {self.uuid}"
            super().save(*args, **kwargs)
            replaces = {
                "{job_title}": self.job.title,
                "{job_requirements}": self.job.requirements,
                "{job_responsibilities}": self.job.responsibilities,
            }
            initial_prompt = reduce(
                lambda acc, key: acc.replace(key, replaces[key]),
                replaces,
                settings.INITIAL_PROMPT_TEMPLATE,
            )
            Message.objects.create(
                chat=self, role=MessageRole.SYSTEM.value, content=initial_prompt
            )
        else:
            super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("interview:details", kwargs={"uuid": self.uuid})

job/models.py
from enum import Enum

from django.db import models
from django.urls import reverse


class JobLevel(Enum):
    JUNIOR = "Júnior"
    PLENO = "Pleno"
    SENIOR = "Sênior"

    @classmethod
    def choices(cls):
        return [(key.value, key.value) for key in cls]


class Job(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    requirements = models.TextField()
    responsibilities = models.TextField()
    level = models.CharField(max_length=10, choices=JobLevel.choices())
    skills = models.ManyToManyField("job.Skill", related_name="jobs")

    def __str__(self):
        return self.title

    def requirements_list(self):
        return self.requirements.split("\n")

    def responsibilities_list(self):
        return self.responsibilities.split("\n")

    def get_absolute_url(self):
        return reverse("job:details", kwargs={"pk": self.pk})


class Skill(models.Model):
    title = models.CharField(max_length=100, unique=True, blank=False, null=False)

    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import render

# Create your views here.

interview/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render

from core.services import GptService
from interview.models import Chat, Message, MessageRole
from job.models import Job


def create(request, job_pk):
    if request.method == "POST":
        job = get_object_or_404(Job, pk=job_pk)
        chat = Chat.objects.create(job=job)
        gpt_service = GptService()
        chat_message = gpt_service.get_chat_message(chat.messages.all())
        chat_message.chat = chat
        chat_message.save()
        return redirect("interview:details", uuid=chat.uuid)
    return HttpResponseNotAllowed(permitted_methods=["POST"])


def details(request, uuid):
    chat = get_object_or_404(Chat, uuid=uuid)
    return render(
        request,
        "interview/details.html",
        {
            "page_title": f"Entrevista: {chat.job.title}",
            "chat": chat,
        },
    )


def create_message(request, chat_uuid):
    chat = get_object_or_404(Chat, uuid=chat_uuid)
    if request.method == "POST" and not chat.completed:
        user_message = request.POST.get("answer")
        Message.objects.create(
            chat=chat,
            role=MessageRole.USER.value,
            content=user_message,
        )
        gpt_service = GptService()
        if chat.messages.filter(role=MessageRole.USER.value).count() >= 5:
            Message.objects.create(
                chat=chat,
                role=MessageRole.SYSTEM.value,
                content="Realize o feedback e não realize mais perguntas.",
            )
            chat.completed = True
            chat.save()
        chat_message = gpt_service.get_chat_message(chat.messages.all())
        chat_message.chat = chat
        chat_message.save()
        return redirect("interview:details", uuid=chat.uuid)
    return HttpResponseNotAllowed(permitted_methods=["POST"])

job/views.py
from django.shortcuts import render, get_object_or_404

from job.models import Job


def list(request):
    return render(
        request,
        "job/list.html",
        {
            "page_title": "Lista de vagas",
            "jobs": Job.objects.prefetch_related("skills").all(),
        },
    )


def details(request, pk):
    job = get_object_or_404(Job, pk=pk)
    return render(
        request,
        "job/details.html",
        {
            "page_title": job.title,
            "job": job,
        },
    )

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />

    {% block styles %}{% endblock styles %}

    <title>TWJobs - {{ page_title }}</title>
  </head>
  <body>
    <nav class="navbar bg-dark" data-bs-theme="dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'job:list' %}">
          <img
            src="https://github.com/treinaweb.png"
            alt="Logo"
            width="24"
            height="24"
            class="d-inline-block align-text-top"
          />
          TWJobs
        </a>
      </div>
    </nav>

    <main>
      <section class="py-5">
        <div class="container">{% block content %} {% endblock %}</div>
      </section>
    </main>

    <footer class="bg-dark fixed-bottom">
      <div class="container">
        <p class="text-white text-center m-0 py-3">TreinaWeb</p>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>

    {% block scripts %}{% endblock scripts %}
  </body>
</html>

interview/templates/interview/details.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ page_title }}</h1>

  {% for message in chat.messages.all %}
    {% if message.role != 'system' %}
      <div class="card mb-3 {% if message.role == 'assistant' %}text-bg-light{% endif %}">
        <div class="card-header d-flex">
          {% if message.role == "assistant" %}
            Entrevistador
          {% else %}
            Candidato
          {% endif %}
        </div>
        <div class="card-body">
          <p class="card-text">{{ message.content|linebreaksbr }}</p>
        </div>
      </div>
    {% endif %}
  {% endfor %}

  <form action="{% url 'interview:create_message' chat_uuid=chat.pk %}" method="post">
    {% csrf_token %}
    <div class="form-floating mb-2">
      <textarea autofocus {% if chat.completed %}disabled{% endif %} style="height: 150px" class="form-control" placeholder="Coloque aqui a sua resposta" id="answer" name="answer"></textarea>
      <label for="answer">Resposta</label>
    </div>
    <button {% if chat.completed %}disabled{% endif %} type="submit" class="btn btn-primary mb-4">Enviar</button>
  </form>

  {% block scripts %}
    <script>
      window.scrollTo(0, document.body.scrollHeight);
    </script>
  {% endblock scripts %}
{% endblock %}

job/templates/job/details.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ page_title }} - {{ job.get_level_display }}</h1>
  <div>
    {% for skill in job.skills.all %}
      <span class="badge text-bg-primary">{{ skill.title }}</span>
    {% endfor %}
  </div>

  <h2 class="mt-3">Descrição</h2>
  <p>{{ job.description|linebreaksbr }}</p>

  <h2 class="mt-3">Requisitos</h2>
  <ul>
    {% for requirement in job.requirements_list %}
      <li>{{ requirement }}</li>
    {% endfor %}
  </ul>

  <h2 class="mt-3">Responsabilidades</h2>
  <ul>
    {% for responsibilitie in job.responsibilities_list %}
      <li>{{ responsibilitie }}</li>
    {% endfor %}
  </ul>

  <form action="{% url 'interview:create' job_pk=job.pk %}" method="post" class="mt-3 mb-5">
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Simular entrevista</button>
  </form>
{% endblock content %}

job/templates/job/list.html
{% extends 'base.html' %}

{% block styles %}
  <style>
    .card-area {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 30px;
    }

    .card {
      max-height: 300px;
      overflow: hidden;
    }

    .card-body {
      display: flex;
      flex-direction: column;
    }

    .card-body .links {
      margin-top: auto;
    }

    .card h5 {
      overflow: hidden;
      display: -webkit-box;
      /* aqui tu força a quantidade de linhas máximas que você quer que apareça */
      -webkit-line-clamp: 3;
      line-clamp: 3;
      -webkit-box-orient: vertical;
    }
  </style>
{% endblock styles %}

{% block content %}
  <h1>{{ page_title }}</h1>

  <div class="card-area mt-4 px-2">
    {% for job in jobs %}
      <div class="card ">
        <div class="card-body">
            <h5 class="card-title fw-bolder">
              {{ job.title }}
            </h5>
            <h6 class="card-subtitle mb-2 tex-body-secondary">{{ job.get_level_display }}</h6 class="card-title">
            <p class="card-text">
              {% for skill in job.skills.all %}
                <span class="badge text-bg-primary">{{ skill.title }}</span>
              {% endfor %}
            </p>
            <div class="links">
              <a href="{% url 'job:details' pk=job.pk %}" class="mt-4">Detalhes</a>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock content %}